require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"

spec "modules.colorscheme"
spec "modules.devicons"
spec "modules.treesitter"
spec "modules.mason"
spec "modules.lspconfig"
spec "modules.schemastore"
spec "modules.cmp"
spec "modules.telescope"
spec "modules.nvimtree"
spec "modules.bufferline"

require "user.lazy"
